import { useEffect, useState } from 'react'
import { ExternalLink, Layers, Loader2, Monitor, Play, Smartphone, X } from 'lucide-react'
import { loadContent } from '../lib/content'

export default function Showcase() {
  const [projects, setProjects] = useState([])
  const [loading, setLoading] = useState(true)
  const [category, setCategory] = useState('all')
  const [preview, setPreview] = useState(null)

  useEffect(() => { loadContent('projects').then(setProjects).catch(() => setProjects([])).finally(() => setLoading(false)) }, [])
  const filtered = category === 'all' ? projects : projects.filter((item) => item.category === category)

  return <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
    <div className="mb-12 text-center"><h1 className="text-3xl font-extrabold text-gray-900 sm:text-4xl dark:text-white">معرض المشاريع</h1><p className="mx-auto mt-4 max-w-2xl text-gray-600 dark:text-gray-400">شغّل محاكاة تطبيقات أندرويد وتجارب الديسكتوب من داخل الموقع.</p></div>
    <div className="mb-10 flex justify-center gap-3"><FilterButton active={category === 'all'} onClick={() => setCategory('all')}><Layers className="mr-2 inline h-4 w-4" />الكل</FilterButton><FilterButton active={category === 'android'} onClick={() => setCategory('android')}><Smartphone className="mr-2 inline h-4 w-4" />أندرويد</FilterButton><FilterButton active={category === 'desktop'} onClick={() => setCategory('desktop')}><Monitor className="mr-2 inline h-4 w-4" />ديسكتاوب</FilterButton></div>
    {loading ? <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-primary-500" /></div> : filtered.length === 0 ? <div className="card py-20 text-center"><Layers className="mx-auto h-12 w-12 text-gray-300" /><p className="mt-4 text-gray-500 dark:text-gray-400">لا توجد مشاريع منشورة بعد.</p></div> : <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((project) => <article key={project.id} className="card overflow-hidden"><div className="h-48 bg-gray-100 dark:bg-gray-800">{project.image && <img src={project.image} alt={project.title} className="h-full w-full object-cover" />}</div><div className="p-5"><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-primary-600 dark:text-primary-400">{project.category === 'android' ? <Smartphone className="h-4 w-4" /> : <Monitor className="h-4 w-4" />}{project.category === 'android' ? 'محاكاة أندرويد' : 'محاكاة ديسكتوب'}</div><h2 className="font-bold text-gray-900 dark:text-white">{project.title}</h2><p className="mt-2 line-clamp-3 text-sm text-gray-600 dark:text-gray-400">{project.description}</p>{project.contentUrl ? <div className="mt-5 flex gap-2"><button onClick={() => setPreview(project)} className="btn-simulator flex-1"><Play className="h-4 w-4 fill-white" />تشغيل المحاكاة</button><a href={project.contentUrl} target="_blank" rel="noopener noreferrer" className="btn-external" aria-label="فتح رابط المحاكاة"><ExternalLink className="h-4 w-4" /></a></div> : <p className="mt-5 text-xs text-gray-400">لم تتم إضافة رابط محاكاة لهذا المشروع.</p>}</div></article>)}</div>}
    {preview && <div className="fixed inset-0 z-[100] flex items-center justify-center p-4" onClick={() => setPreview(null)}><div className="absolute inset-0 bg-gray-950/80 backdrop-blur-sm" /><div className="relative z-10 w-full max-w-5xl overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-gray-900" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between border-b border-gray-200 px-5 py-4 dark:border-gray-800"><div><h2 className="font-bold text-gray-900 dark:text-white">{preview.title}</h2><p className="text-xs text-gray-500">{preview.category === 'android' ? 'محاكاة أندرويد' : 'محاكاة ديسكتوب'}</p></div><button onClick={() => setPreview(null)} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-800" aria-label="إغلاق"><X className="h-5 w-5" /></button></div><div className="relative aspect-video bg-gray-950"><iframe src={preview.contentUrl} title={`محاكاة ${preview.title}`} className="h-full w-full" allow="fullscreen; autoplay; clipboard-read; clipboard-write" allowFullScreen /></div><div className="flex items-center justify-between gap-4 border-t border-gray-200 px-5 py-3 dark:border-gray-800"><p className="text-xs text-gray-500 dark:text-gray-400">إذا منع الرابط العرض داخل النافذة، استخدم زر الفتح الخارجي.</p><a href={preview.contentUrl} target="_blank" rel="noopener noreferrer" className="inline-flex shrink-0 items-center gap-2 text-sm font-semibold text-primary-600 hover:underline"><ExternalLink className="h-4 w-4" />فتح في تبويب</a></div></div></div>}
  </div>
}

function FilterButton({ active, onClick, children }) {
  return <button onClick={onClick} className={`rounded-full px-5 py-2.5 text-sm font-medium transition-all ${active ? 'bg-gradient-to-l from-primary-600 to-secondary-600 text-white shadow-md shadow-primary-600/20' : 'border border-gray-200 bg-white text-gray-700 hover:border-primary-300 hover:text-primary-700 dark:border-gray-800 dark:bg-gray-900 dark:text-gray-300 dark:hover:border-primary-700'}`}>{children}</button>
}
